name: Rittri89
version: 0.1.0.0
license: BSD-3-Clause
author: "Satoshi Takimoto"
maintainer: "wasabi.nvim.st@gmail.com"
copyright: "2025 Satoshi Takimoto"

language: GHC2024

default-extensions:
  - AllowAmbiguousTypes
  - BlockArguments
  - CPP
  - DerivingVia
  - DeriveAnyClass
  - DuplicateRecordFields
  - MultilineStrings
  - MultiParamTypeClasses
  - NoFieldSelectors
  - OrPatterns
  - OverloadedLabels
  - OverloadedStrings
  - OverloadedRecordDot
  - PatternSynonyms
  - QualifiedDo
  - RecordWildCards
  - Strict
  - TypeFamilies
  - ViewPatterns

dependencies:
  - base >= 4.7 && < 5
  - containers
  - haskeline
  - megaparsec
  - multiset
  - text

ghc-options:
  - -Wall
  - -Wcompat
  - -Widentities
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wmissing-deriving-strategies
  - -Wmissing-export-lists
  - -Wmissing-home-modules
  - -Wpartial-fields
  - -Wredundant-constraints
  - -O2
  - -funbox-strict-fields

executables:
  Rittri89:
    main: Main.hs
    source-dirs: .
